### PR TITLE
toleration and affinity support added

### PR DESCRIPTION
**Pull request by AdheipSingh**
Added support for tolerations and affinity in the InfluxdbSpec, and in the statefulset spec file.
Refer to this https://github.com/influxdata/influxdata-operator/issues/10.

### CODE REVIEW

**Comment by AdheipSingh** [comment]
Added support for node selector and Env's. Refer to #10.

**Comment by gitirabassi** [comment]
@AdheipSingh can you merge this

**Comment by AdheipSingh** [comment]
I dont have the permissions @gitirabassi . By the way is this projected active ?

**Comment by gitirabassi** [comment]
@AdheipSingh we'll be migrating this to another repo and picking up development again

**Comment by AdheipSingh** [comment]
@gitirabassi that's great, happy to contribute to it.

**Pull request merged**
